apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: s3-exporter
  namespace: kube-system
spec:
  chart:
    spec:
      chart: charts/s3-exporter
      sourceRef:
        kind: GitRepository
        name: kubermatic-git
        namespace: kubermatic
  interval: 5m
  valuesFrom:
    - kind: Secret
      name: kubermatic-values
      valuesKey: values.yaml
